services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - .:/usr/src/app
    networks:
      - my_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

networks:
  my_network:
    driver: bridge
